In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime
pd.set_option('display.max_columns', None)

In [7]:
del df

In [13]:
df= pd.read_excel('caraccidentslosangeles.xlsx')

In [14]:
df.columns

Index(['ID', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat', 'Start_Lng',
       'End_Lat', 'End_Lng', 'Distance(mi)', 'Description', 'Number', 'Street',
       'Side', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [16]:
df.shape

(68956, 47)

In [75]:
df.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Number,Street,Side,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-5236,2,2016-03-22 19:36:44,2016-03-23 01:36:44,34.09256,-118.206220,34.092560,-118.206220,0.000,At Avenue 43 - Accident.,NaN,CA-110 N,R,Los Angeles,Los Angeles,CA,90031,US,US/Pacific,KCQT,2016-03-22 19:47:00,64.0,NaN,24.0,30.00,10.0,NNW,9.2,NaN,Clear,False,False,False,False,False,False,False,False,False,True,False,False,False,Night,Night,Day,Day
1,A-5239,2,2016-03-22 20:59:43,2016-03-23 02:59:43,33.94819,-118.279730,33.946760,-118.279750,0.099,At Century Blvd - Accident.,NaN,I-110 S,R,Los Angeles,Los Angeles,CA,90003,US,US/Pacific,KHHR,2016-03-22 20:53:00,64.0,NaN,23.0,30.02,10.0,NNW,11.5,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night
2,A-5254,3,2016-03-23 07:59:47,2016-03-23 13:59:47,34.02330,-118.172880,34.021380,-118.173390,0.136,At Whittier Blvd/Olympic Blvd - Accident.,NaN,Long Beach Fwy S,R,Los Angeles,Los Angeles,CA,90022,US,US/Pacific,KCQT,2016-03-23 07:47:00,55.9,NaN,53.0,30.11,10.0,Calm,NaN,NaN,Clear,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
3,A-5272,2,2016-03-23 11:50:32,2016-03-23 17:50:32,34.14470,-118.278650,34.141040,-118.277840,0.257,At Colorado St - Accident.,NaN,Golden State Fwy S,R,Los Angeles,Los Angeles,CA,90027,US,US/Pacific,KCQT,2016-03-23 11:47:00,73.9,NaN,14.0,30.15,10.0,Calm,NaN,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
4,A-5274,2,2016-03-23 12:16:45,2016-03-23 18:16:45,34.09914,-118.251853,34.099817,-118.251396,0.054,At I-5/Golden State Fwy - Accident. Left lane ...,NaN,CA-2 S,R,Los Angeles,Los Angeles,CA,90039,US,US/Pacific,KCQT,2016-03-23 11:47:00,73.9,NaN,14.0,30.15,10.0,Calm,NaN,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day

In [18]:
df['Number'].tail()

68951   NaN
68952   NaN
68953   NaN
68954   NaN
68955   NaN
Name: Number, dtype: float64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68956 entries, 0 to 68955
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     68956 non-null  object
 1   Severity               68956 non-null  int64
 2   Start_Time             68956 non-null  object
 3   End_Time               68956 non-null  object
 4   Start_Lat              68956 non-null  float64
 5   Start_Lng              68956 non-null  float64
 6   End_Lat                68956 non-null  float64
 7   End_Lng                68956 non-null  float64
 8   Distance(mi)           68956 non-null  float64
 9   Description            68956 non-null  object
 10  Number                 22123 non-null  float64
 11  Street                 68956 non-null  object
 12  Side                   68956 non-null  object
 13  City                   68956 non-null  object
 14  County                 68956 non-null  object
 15  State                  68956 non-null  object
 16  Zipcode                68956 non-null  object
 17  Country                68956 non-null  object
 18  Timezone               68956 non-null  object
 19  Airport_Code           68956 non-null  object
 20  Weather_Timestamp      68733 non-null  object
 21  Temperature(F)         68414 non-null  float64
 22  Wind_Chill(F)          56594 non-null  float64
 23  Humidity(%)            68404 non-null  float64
 24  Pressure(in)           68459 non-null  float64
 25  Visibility(mi)         68630 non-null  float64
 26  Wind_Direction         67592 non-null  object
 27  Wind_Speed(mph)        63330 non-null  float64
 28  Precipitation(in)      58428 non-null  float64
 29  Weather_Condition      68655 non-null  object
 30  Amenity                68956 non-null  bool
 31  Bump                   68956 non-null  bool
 32  Crossing               68956 non-null  bool
 33  Give_Way               68956 non-null  bool
 34  Junction               68956 non-null  bool
 35  No_Exit                68956 non-null  bool
 36  Railway                68956 non-null  bool
 37  Roundabout             68956 non-null  bool
 38  Station                68956 non-null  bool
 39  Stop                   68956 non-null  bool
 40  Traffic_Calming        68956 non-null  bool
 41  Traffic_Signal         68956 non-null  bool
 42  Turning_Loop           68956 non-null  bool
 43  Sunrise_Sunset         68956 non-null  object
 44  Civil_Twilight         68956 non-null  object
 45  Nautical_Twilight      68956 non-null  object
 46  Astronomical_Twilight  68956 non-null  object
dtypes: bool(13), float64(13), int64(1), object(20)
memory usage: 18.7+ MB

In [15]:
df.isna().sum()

ID                           0
Severity                     0
Start_Time                   0
End_Time                     0
Start_Lat                    0
Start_Lng                    0
End_Lat                      0
End_Lng                      0
Distance(mi)                 0
Description                  0
Number                   46833
Street                       0
Side                         0
City                         0
County                       0
State                        0
Zipcode                      0
Country                      0
Timezone                     0
Airport_Code                 0
Weather_Timestamp          223
Temperature(F)             542
Wind_Chill(F)            12362
Humidity(%)                552
Pressure(in)               497
Visibility(mi)             326
Wind_Direction            1364
Wind_Speed(mph)           5626
Precipitation(in)        10528
Weather_Condition          301
Amenity                      0
Bump                         0
Crossing                     0
Give_Way                     0
Junction                     0
No_Exit                      0
Railway                      0
Roundabout                   0
Station                      0
Stop                         0
Traffic_Calming              0
Traffic_Signal               0
Turning_Loop                 0
Sunrise_Sunset               0
Civil_Twilight               0
Nautical_Twilight            0
Astronomical_Twilight        0
dtype: int64

In [40]:
df['Zipcode'].nunique()

5857

In [42]:
df['Street'].nunique()

1604

In [19]:
df['Weather_Condition'].unique()

array(['Clear', 'Overcast', 'Light Rain', 'Mostly Cloudy',
       'Partly Cloudy', 'Scattered Clouds', 'Haze', 'Rain', 'Mist',
       'Smoke', 'Heavy Rain', 'Fog', nan, 'Patches of Fog', 'Fair',
       'Cloudy', 'Light Rain / Windy', 'Heavy Rain / Windy',
       'Heavy T-Storm', 'Fair / Windy', 'Duststorm',
       'Light Rain with Thunder', 'T-Storm', 'Rain / Windy',
       'Mostly Cloudy / Windy', 'Light Drizzle', 'Partly Cloudy / Windy',
       'Blowing Dust', 'Thunder', 'Shallow Fog', 'Thunderstorm'],
      dtype=object)

In [20]:
df['Weather_Timestamp'].unique()

array(['2016-03-22 19:47:00', '2016-03-22 20:53:00',
       '2016-03-23 07:47:00', ..., '2019-08-23 12:52:00',
       '2019-08-23 13:52:00', '2019-08-23 15:51:00'], dtype=object)

In [38]:
df['Timezone'].unique()

array(['US/Pacific'], dtype=object)

In [26]:
df['Sunrise_Sunset'].unique()

array(['Night', 'Day'], dtype=object)

In [27]:
df['Civil_Twilight'].unique()

array(['Night', 'Day'], dtype=object)

In [46]:
df['Description'].head()

0                             At Avenue 43 - Accident.
1                          At Century Blvd - Accident.
2            At Whittier Blvd/Olympic Blvd - Accident.
3                           At Colorado St - Accident.
4    At I-5/Golden State Fwy - Accident. Left lane ...
Name: Description, dtype: object

In [34]:
df['Street']

0                  CA-110 N
1                   I-110 S
2          Long Beach Fwy S
3        Golden State Fwy S
4                    CA-2 S
                ...
68951       San Diego Fwy S
68952       Hollywood Fwy S
68953          Harbor Fwy N
68954       Hollywood Fwy S
68955               I-405 N
Name: Street, Length: 68956, dtype: object

In [35]:
df['Number'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Number, dtype: float64

In [37]:
df['County'].unique()

array(['Los Angeles'], dtype=object)

In [32]:
df.tail()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Number,Street,Side,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
68951,A-2844906,2,2019-08-22 17:07:14,2019-08-22 17:36:02,34.03693,-118.43877,34.02559,-118.42918,0.957,At I-10/Santa Monica Fwy - Accident.,NaN,San Diego Fwy S,R,Los Angeles,Los Angeles,CA,90064,US,US/Pacific,KSMO,2019-08-22 16:51:00,72.0,72.0,76.0,29.57,10.0,SW,8.0,0.0,Fair,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
68952,A-2845306,3,2019-08-23 04:04:48,2019-08-23 04:33:53,34.07579,-118.27668,34.07431,-118.27225,0.273,At Benton Way/Rampart Blvd/Exit 5A - Accident.,NaN,Hollywood Fwy S,R,Los Angeles,Los Angeles,CA,90026,US,US/Pacific,KCQT,2019-08-23 03:52:00,67.0,67.0,79.0,29.62,7.0,CALM,0.0,0.0,Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night
68953,A-2845310,2,2019-08-23 12:52:31,2019-08-23 13:20:14,34.02379,-118.27639,34.02576,-118.27529,0.150,At 28th St - Accident.,NaN,Harbor Fwy N,R,Los Angeles,Los Angeles,CA,90007,US,US/Pacific,KCQT,2019-08-23 12:52:00,81.0,81.0,49.0,29.66,8.0,CALM,0.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
68954,A-2845313,2,2019-08-23 13:42:50,2019-08-23 14:10:06,34.07061,-118.26391,34.06974,-118.26155,0.148,At Glendale Blvd/Union Ave - Accident.,NaN,Hollywood Fwy S,R,Los Angeles,Los Angeles,CA,90026,US,US/Pacific,KCQT,2019-08-23 13:52:00,82.0,82.0,47.0,29.65,9.0,CALM,0.0,0.0,Fair,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
68955,A-2845325,2,2019-08-23 15:45:43,2019-08-23 16:14:31,34.04365,-118.44373,34.04934,-118.44842,0.476,At CA-2/Santa Monica Blvd/Exit 55A - Accident.,NaN,I-405 N,R,Los Angeles,Los Angeles,CA,90025,US,US/Pacific,KSMO,2019-08-23 15:51:00,74.0,74.0,66.0,29.64,10.0,W,8.0,0.0,Fair,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day

In [22]:
df['Start_Time'].max()

'2021-12-31 21:47:00'

In [23]:
df['Start_Time'].min()

'2016-03-22 19:36:44'

In [24]:
df['Crossing'].head()

0    False
1    False
2    False
3    False
4    False
Name: Crossing, dtype: bool

In [47]:
df1 = df.copy()

In [49]:
df1.drop('Number',axis = 1, inplace = True)

In [51]:
df1.drop('Nautical_Twilight',axis = 1, inplace = True)

In [54]:
listofcols = list(df.columns)

In [55]:
listofcols

['ID',
 'Severity',
 'Start_Time',
 'End_Time',
 'Start_Lat',
 'Start_Lng',
 'End_Lat',
 'End_Lng',
 'Distance(mi)',
 'Description',
 'Number',
 'Street',
 'Side',
 'City',
 'County',
 'State',
 'Zipcode',
 'Country',
 'Timezone',
 'Airport_Code',
 'Weather_Timestamp',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Direction',
 'Wind_Speed(mph)',
 'Precipitation(in)',
 'Weather_Condition',
 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',
 'Turning_Loop',
 'Sunrise_Sunset',
 'Civil_Twilight',
 'Nautical_Twilight',
 'Astronomical_Twilight']

In [59]:
colstokeep = ['ID',
 'Severity',
 'Start_Time',
 'End_Time',
 'Start_Lat',
 'Start_Lng',
 'End_Lat',
 'End_Lng',
 'Distance(mi)',
 'City',
 'Zipcode',
 'Airport_Code',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Visibility(mi)',
 'Precipitation(in)',
 'Weather_Condition',
 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',
 'Turning_Loop',
 'Civil_Twilight'
]

In [60]:
colstokeep

['ID',
 'Severity',
 'Start_Time',
 'End_Time',
 'Start_Lat',
 'Start_Lng',
 'End_Lat',
 'End_Lng',
 'Distance(mi)',
 'City',
 'Zipcode',
 'Airport_Code',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Visibility(mi)',
 'Precipitation(in)',
 'Weather_Condition',
 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',
 'Turning_Loop',
 'Civil_Twilight']

In [61]:
dfnew = df[colstokeep]

In [62]:
dfnew.columns

Index(['ID', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat', 'Start_Lng',
       'End_Lat', 'End_Lng', 'Distance(mi)', 'City', 'Zipcode', 'Airport_Code',
       'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)', 'Visibility(mi)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Civil_Twilight'],
      dtype='object')

In [63]:
dfnew.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),City,Zipcode,Airport_Code,Temperature(F),Wind_Chill(F),Humidity(%),Visibility(mi),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Civil_Twilight
0,A-5236,2,2016-03-22 19:36:44,2016-03-23 01:36:44,34.09256,-118.206220,34.092560,-118.206220,0.000,Los Angeles,90031,KCQT,64.0,NaN,24.0,10.0,NaN,Clear,False,False,False,False,False,False,False,False,False,True,False,False,False,Night
1,A-5239,2,2016-03-22 20:59:43,2016-03-23 02:59:43,33.94819,-118.279730,33.946760,-118.279750,0.099,Los Angeles,90003,KHHR,64.0,NaN,23.0,10.0,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Night
2,A-5254,3,2016-03-23 07:59:47,2016-03-23 13:59:47,34.02330,-118.172880,34.021380,-118.173390,0.136,Los Angeles,90022,KCQT,55.9,NaN,53.0,10.0,NaN,Clear,False,False,False,False,True,False,False,False,False,False,False,False,False,Day
3,A-5272,2,2016-03-23 11:50:32,2016-03-23 17:50:32,34.14470,-118.278650,34.141040,-118.277840,0.257,Los Angeles,90027,KCQT,73.9,NaN,14.0,10.0,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day
4,A-5274,2,2016-03-23 12:16:45,2016-03-23 18:16:45,34.09914,-118.251853,34.099817,-118.251396,0.054,Los Angeles,90039,KCQT,73.9,NaN,14.0,10.0,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day

In [64]:
dfnew.shape

(68956, 32)

In [65]:
dfnew.isna().sum()

ID                       0
Severity                 0
Start_Time               0
End_Time                 0
Start_Lat                0
Start_Lng                0
End_Lat                  0
End_Lng                  0
Distance(mi)             0
City                     0
Zipcode                  0
Airport_Code             0
Temperature(F)         542
Wind_Chill(F)        12362
Humidity(%)            552
Visibility(mi)         326
Precipitation(in)    10528
Weather_Condition      301
Amenity                  0
Bump                     0
Crossing                 0
Give_Way                 0
Junction                 0
No_Exit                  0
Railway                  0
Roundabout               0
Station                  0
Stop                     0
Traffic_Calming          0
Traffic_Signal           0
Turning_Loop             0
Civil_Twilight           0
dtype: int64

In [66]:
dfnew.dropna(inplace = True)

C:\Users\kathe\AppData\Local\Temp\ipykernel_21488\1722201879.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfnew.dropna(inplace = True)

In [68]:
dfnew.isna().sum()

ID                   0
Severity             0
Start_Time           0
End_Time             0
Start_Lat            0
Start_Lng            0
End_Lat              0
End_Lng              0
Distance(mi)         0
City                 0
Zipcode              0
Airport_Code         0
Temperature(F)       0
Wind_Chill(F)        0
Humidity(%)          0
Visibility(mi)       0
Precipitation(in)    0
Weather_Condition    0
Amenity              0
Bump                 0
Crossing             0
Give_Way             0
Junction             0
No_Exit              0
Railway              0
Roundabout           0
Station              0
Stop                 0
Traffic_Calming      0
Traffic_Signal       0
Turning_Loop         0
Civil_Twilight       0
dtype: int64

In [69]:
dfnew.to_csv('LAFinal.csv')

In [70]:
dfnew.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56471 entries, 5364 to 68955
Data columns (total 32 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 56471 non-null  object
 1   Severity           56471 non-null  int64
 2   Start_Time         56471 non-null  object
 3   End_Time           56471 non-null  object
 4   Start_Lat          56471 non-null  float64
 5   Start_Lng          56471 non-null  float64
 6   End_Lat            56471 non-null  float64
 7   End_Lng            56471 non-null  float64
 8   Distance(mi)       56471 non-null  float64
 9   City               56471 non-null  object
 10  Zipcode            56471 non-null  object
 11  Airport_Code       56471 non-null  object
 12  Temperature(F)     56471 non-null  float64
 13  Wind_Chill(F)      56471 non-null  float64
 14  Humidity(%)        56471 non-null  float64
 15  Visibility(mi)     56471 non-null  float64
 16  Precipitation(in)  56471 non-null  float64
 17  Weather_Condition  56471 non-null  object
 18  Amenity            56471 non-null  bool
 19  Bump               56471 non-null  bool
 20  Crossing           56471 non-null  bool
 21  Give_Way           56471 non-null  bool
 22  Junction           56471 non-null  bool
 23  No_Exit            56471 non-null  bool
 24  Railway            56471 non-null  bool
 25  Roundabout         56471 non-null  bool
 26  Station            56471 non-null  bool
 27  Stop               56471 non-null  bool
 28  Traffic_Calming    56471 non-null  bool
 29  Traffic_Signal     56471 non-null  bool
 30  Turning_Loop       56471 non-null  bool
 31  Civil_Twilight     56471 non-null  object
dtypes: bool(13), float64(10), int64(1), object(8)
memory usage: 9.3+ MB

In [72]:
dfnew['Start_Time'] = pd.to_datetime(dfnew['Start_Time'])

C:\Users\kathe\AppData\Local\Temp\ipykernel_21488\1397742529.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfnew['Start_Time'] = pd.to_datetime(dfnew['Start_Time'])

In [73]:
dfnew['End_Time'] = pd.to_datetime(dfnew['End_Time'])

C:\Users\kathe\AppData\Local\Temp\ipykernel_21488\3402304659.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfnew['End_Time'] = pd.to_datetime(dfnew['End_Time'])

In [74]:
dfnew.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56471 entries, 5364 to 68955
Data columns (total 32 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 56471 non-null  object
 1   Severity           56471 non-null  int64
 2   Start_Time         56471 non-null  datetime64[ns]
 3   End_Time           56471 non-null  datetime64[ns]
 4   Start_Lat          56471 non-null  float64
 5   Start_Lng          56471 non-null  float64
 6   End_Lat            56471 non-null  float64
 7   End_Lng            56471 non-null  float64
 8   Distance(mi)       56471 non-null  float64
 9   City               56471 non-null  object
 10  Zipcode            56471 non-null  object
 11  Airport_Code       56471 non-null  object
 12  Temperature(F)     56471 non-null  float64
 13  Wind_Chill(F)      56471 non-null  float64
 14  Humidity(%)        56471 non-null  float64
 15  Visibility(mi)     56471 non-null  float64
 16  Precipitation(in)  56471 non-null  float64
 17  Weather_Condition  56471 non-null  object
 18  Amenity            56471 non-null  bool
 19  Bump               56471 non-null  bool
 20  Crossing           56471 non-null  bool
 21  Give_Way           56471 non-null  bool
 22  Junction           56471 non-null  bool
 23  No_Exit            56471 non-null  bool
 24  Railway            56471 non-null  bool
 25  Roundabout         56471 non-null  bool
 26  Station            56471 non-null  bool
 27  Stop               56471 non-null  bool
 28  Traffic_Calming    56471 non-null  bool
 29  Traffic_Signal     56471 non-null  bool
 30  Turning_Loop       56471 non-null  bool
 31  Civil_Twilight     56471 non-null  object
dtypes: bool(13), datetime64[ns](2), float64(10), int64(1), object(6)
memory usage: 9.3+ MB

In [76]:
dfnew['StartYear'] = dfnew['Start_Time'].dt.year

C:\Users\kathe\AppData\Local\Temp\ipykernel_21488\596517285.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfnew['StartYear'] = dfnew['Start_Time'].dt.year

In [77]:
dfnew['StartMonth'] = dfnew['Start_Time'].dt.month

C:\Users\kathe\AppData\Local\Temp\ipykernel_21488\3799390662.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfnew['StartMonth'] = dfnew['Start_Time'].dt.month

In [78]:
dfnew.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56471 entries, 5364 to 68955
Data columns (total 34 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 56471 non-null  object
 1   Severity           56471 non-null  int64
 2   Start_Time         56471 non-null  datetime64[ns]
 3   End_Time           56471 non-null  datetime64[ns]
 4   Start_Lat          56471 non-null  float64
 5   Start_Lng          56471 non-null  float64
 6   End_Lat            56471 non-null  float64
 7   End_Lng            56471 non-null  float64
 8   Distance(mi)       56471 non-null  float64
 9   City               56471 non-null  object
 10  Zipcode            56471 non-null  object
 11  Airport_Code       56471 non-null  object
 12  Temperature(F)     56471 non-null  float64
 13  Wind_Chill(F)      56471 non-null  float64
 14  Humidity(%)        56471 non-null  float64
 15  Visibility(mi)     56471 non-null  float64
 16  Precipitation(in)  56471 non-null  float64
 17  Weather_Condition  56471 non-null  object
 18  Amenity            56471 non-null  bool
 19  Bump               56471 non-null  bool
 20  Crossing           56471 non-null  bool
 21  Give_Way           56471 non-null  bool
 22  Junction           56471 non-null  bool
 23  No_Exit            56471 non-null  bool
 24  Railway            56471 non-null  bool
 25  Roundabout         56471 non-null  bool
 26  Station            56471 non-null  bool
 27  Stop               56471 non-null  bool
 28  Traffic_Calming    56471 non-null  bool
 29  Traffic_Signal     56471 non-null  bool
 30  Turning_Loop       56471 non-null  bool
 31  Civil_Twilight     56471 non-null  object
 32  StartYear          56471 non-null  int64
 33  StartMonth         56471 non-null  int64
dtypes: bool(13), datetime64[ns](2), float64(10), int64(3), object(6)
memory usage: 10.2+ MB

In [79]:
dfnew.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),City,Zipcode,Airport_Code,Temperature(F),Wind_Chill(F),Humidity(%),Visibility(mi),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Civil_Twilight,StartYear,StartMonth
5364,A-225042,2,2021-12-01 12:22:00,2021-12-01 12:45:00,33.961177,-118.282005,33.960012,-118.281179,0.093,Los Angeles,90003-2752,KHHR,67.0,67.0,63.0,4.0,0.0,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,2021,12
5365,A-225056,2,2021-09-08 17:37:00,2021-09-08 20:05:58,33.916425,-118.269578,33.917889,-118.265243,0.268,Los Angeles,90061-2357,KHHR,72.0,72.0,71.0,10.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,2021,9
5366,A-225142,2,2021-11-06 15:53:00,2021-11-06 17:54:29,33.989157,-118.285657,33.989159,-118.282055,0.206,Los Angeles,90044-6351,KHHR,63.0,63.0,72.0,4.0,0.0,Haze,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,2021,11
5367,A-225143,2,2021-07-30 12:52:17,2021-07-30 14:55:08,33.989163,-118.284854,33.989161,-118.282188,0.153,Los Angeles,90044-6359,KHHR,73.0,73.0,64.0,10.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,2021,7
5368,A-225144,2,2021-03-16 04:35:30,2021-03-16 14:58:00,33.989156,-118.285940,33.989153,-118.280806,0.294,Los Angeles,90044-6360,KHHR,46.0,46.0,61.0,10.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,2021,3

In [80]:
dfnew['Start_Time'].head()

5364   2021-12-01 12:22:00
5365   2021-09-08 17:37:00
5366   2021-11-06 15:53:00
5367   2021-07-30 12:52:17
5368   2021-03-16 04:35:30
Name: Start_Time, dtype: datetime64[ns]

In [83]:
dfnew['StartDay'] = dfnew['Start_Time'].dt.day_of_week

C:\Users\kathe\AppData\Local\Temp\ipykernel_21488\395169355.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfnew['StartDay'] = dfnew['Start_Time'].dt.day_of_week

In [84]:
dfnew['StartDay'].head()

5364    2
5365    2
5366    5
5367    4
5368    1
Name: StartDay, dtype: int64

In [85]:
dfnew['StartTime'] = pd.to_datetime(dfnew['Start_Time']).dt.strftime('%H:%M:%S')

C:\Users\kathe\AppData\Local\Temp\ipykernel_21488\1108534620.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfnew['StartTime'] = pd.to_datetime(dfnew['Start_Time']).dt.strftime('%H:%M:%S')

In [86]:
dfnew['StartTime'].head()

5364    12:22:00
5365    17:37:00
5366    15:53:00
5367    12:52:17
5368    04:35:30
Name: StartTime, dtype: object

In [87]:
dfnew.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),City,Zipcode,Airport_Code,Temperature(F),Wind_Chill(F),Humidity(%),Visibility(mi),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Civil_Twilight,StartYear,StartMonth,StartDay,StartTime
5364,A-225042,2,2021-12-01 12:22:00,2021-12-01 12:45:00,33.961177,-118.282005,33.960012,-118.281179,0.093,Los Angeles,90003-2752,KHHR,67.0,67.0,63.0,4.0,0.0,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,2021,12,2,12:22:00
5365,A-225056,2,2021-09-08 17:37:00,2021-09-08 20:05:58,33.916425,-118.269578,33.917889,-118.265243,0.268,Los Angeles,90061-2357,KHHR,72.0,72.0,71.0,10.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,2021,9,2,17:37:00
5366,A-225142,2,2021-11-06 15:53:00,2021-11-06 17:54:29,33.989157,-118.285657,33.989159,-118.282055,0.206,Los Angeles,90044-6351,KHHR,63.0,63.0,72.0,4.0,0.0,Haze,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,2021,11,5,15:53:00
5367,A-225143,2,2021-07-30 12:52:17,2021-07-30 14:55:08,33.989163,-118.284854,33.989161,-118.282188,0.153,Los Angeles,90044-6359,KHHR,73.0,73.0,64.0,10.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,2021,7,4,12:52:17
5368,A-225144,2,2021-03-16 04:35:30,2021-03-16 14:58:00,33.989156,-118.285940,33.989153,-118.280806,0.294,Los Angeles,90044-6360,KHHR,46.0,46.0,61.0,10.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,2021,3,1,04:35:30

In [88]:
dfnew['StartDate'] = pd.to_datetime(dfnew['Start_Time']).dt.date

C:\Users\kathe\AppData\Local\Temp\ipykernel_21488\3658621450.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfnew['StartDate'] = pd.to_datetime(dfnew['Start_Time']).dt.date

In [89]:
dfnew.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),City,Zipcode,Airport_Code,Temperature(F),Wind_Chill(F),Humidity(%),Visibility(mi),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Civil_Twilight,StartYear,StartMonth,StartDay,StartTime,StartDate
5364,A-225042,2,2021-12-01 12:22:00,2021-12-01 12:45:00,33.961177,-118.282005,33.960012,-118.281179,0.093,Los Angeles,90003-2752,KHHR,67.0,67.0,63.0,4.0,0.0,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,2021,12,2,12:22:00,2021-12-01
5365,A-225056,2,2021-09-08 17:37:00,2021-09-08 20:05:58,33.916425,-118.269578,33.917889,-118.265243,0.268,Los Angeles,90061-2357,KHHR,72.0,72.0,71.0,10.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,2021,9,2,17:37:00,2021-09-08
5366,A-225142,2,2021-11-06 15:53:00,2021-11-06 17:54:29,33.989157,-118.285657,33.989159,-118.282055,0.206,Los Angeles,90044-6351,KHHR,63.0,63.0,72.0,4.0,0.0,Haze,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,2021,11,5,15:53:00,2021-11-06
5367,A-225143,2,2021-07-30 12:52:17,2021-07-30 14:55:08,33.989163,-118.284854,33.989161,-118.282188,0.153,Los Angeles,90044-6359,KHHR,73.0,73.0,64.0,10.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,2021,7,4,12:52:17,2021-07-30
5368,A-225144,2,2021-03-16 04:35:30,2021-03-16 14:58:00,33.989156,-118.285940,33.989153,-118.280806,0.294,Los Angeles,90044-6360,KHHR,46.0,46.0,61.0,10.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,2021,3,1,04:35:30,2021-03-16

In [90]:
dfnew['EndDate'] = pd.to_datetime(dfnew['End_Time']).dt.date

C:\Users\kathe\AppData\Local\Temp\ipykernel_21488\871911445.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfnew['EndDate'] = pd.to_datetime(dfnew['End_Time']).dt.date

In [91]:
dfnew['EndTime'] = pd.to_datetime(dfnew['End_Time']).dt.strftime('%H:%M:%S')

C:\Users\kathe\AppData\Local\Temp\ipykernel_21488\3546688436.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfnew['EndTime'] = pd.to_datetime(dfnew['End_Time']).dt.strftime('%H:%M:%S')

In [92]:
dfnew.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),City,Zipcode,Airport_Code,Temperature(F),Wind_Chill(F),Humidity(%),Visibility(mi),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Civil_Twilight,StartYear,StartMonth,StartDay,StartTime,StartDate,EndDate,EndTime
5364,A-225042,2,2021-12-01 12:22:00,2021-12-01 12:45:00,33.961177,-118.282005,33.960012,-118.281179,0.093,Los Angeles,90003-2752,KHHR,67.0,67.0,63.0,4.0,0.0,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,2021,12,2,12:22:00,2021-12-01,2021-12-01,12:45:00
5365,A-225056,2,2021-09-08 17:37:00,2021-09-08 20:05:58,33.916425,-118.269578,33.917889,-118.265243,0.268,Los Angeles,90061-2357,KHHR,72.0,72.0,71.0,10.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,2021,9,2,17:37:00,2021-09-08,2021-09-08,20:05:58
5366,A-225142,2,2021-11-06 15:53:00,2021-11-06 17:54:29,33.989157,-118.285657,33.989159,-118.282055,0.206,Los Angeles,90044-6351,KHHR,63.0,63.0,72.0,4.0,0.0,Haze,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,2021,11,5,15:53:00,2021-11-06,2021-11-06,17:54:29
5367,A-225143,2,2021-07-30 12:52:17,2021-07-30 14:55:08,33.989163,-118.284854,33.989161,-118.282188,0.153,Los Angeles,90044-6359,KHHR,73.0,73.0,64.0,10.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,2021,7,4,12:52:17,2021-07-30,2021-07-30,14:55:08
5368,A-225144,2,2021-03-16 04:35:30,2021-03-16 14:58:00,33.989156,-118.285940,33.989153,-118.280806,0.294,Los Angeles,90044-6360,KHHR,46.0,46.0,61.0,10.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,2021,3,1,04:35:30,2021-03-16,2021-03-16,14:58:00

In [93]:
dfnew.to_csv('LAFinalTimes.csv')